<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/estilo_index.css">
   
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- CSS only -->
 
    <title>inicio</title>
</head>
<body>
<header>
   
  <nav>
      <a href="#marcador1">inicio</a>
      <a href="#marcador2">Quienes somos</a>
      <a href="#marcador3">Servicios</a>
      <a href="#marcador4">Contactenos</a>
      <a href="registro.php">Registrarce</a>
      <a href="login.php">unirse</a>
  </nav>

 
 
 <!-- texto que va dentro de la ola-->
 <section class="texto-header">
    <h1>Aprende y comparte conocimientos totalmente gratis</h1>

 </section>
 <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
 <!-- codigo de el efecto de ola-->
 <div  class="ola" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C150.00,150.00 360.38,-7.42 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>
</header>
 

<a name="marcador1"></a>
<div class="contenedor">
 <h2  class="titulo1 ">Te ofrecemos las siguientes categorias</h2>
 
 <div id="explicacion">
 
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" id="slider1" src="img/slider.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Maquillaje</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/mecanica.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Mecanica</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/cocina.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Gastronomía</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/idiomas.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Idiomas</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/programacion.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Desarrollo de software</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/construccion.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Construcción</h4>
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" id="slider1" src="img/jardineria.jpg">
          <div class="carousel-caption d-none d-md-block">
            <h4 id="texto-slider">Jardinería</h4>
          </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/pintores.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Pintura</h4>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" id="slider1" src="img/diseño_interiores.jpg">
        <div class="carousel-caption d-none d-md-block">
          <h4 id="texto-slider">Diseño de interiores</h4>
        </div>
      </div>


    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
 </div>


  <p>Esta es la gran oportunidad que siempre estuviste esperando, en esta red social podras encontrar muchos cursos de todas
     las categorias que necesites y lo mejor, de una forma 100% gratuita; 
     pero eso no es todo, tambien te brindamos la oportunidad de que tu crees tus propios cursos en donde podrás ofrecer todos tus conocimientos.
     No lo pienses más y haz parte de nuestra red social
  </p>
 </div>

 

<a name="marcador2"></a>
 <h2 class="titulo2">¿Quienés somos?</h2>
 <div class="explicacion2">
    <img class="img2"src="img/jovenes.jpg" alt="">
    <p>Somos un grupo de estudiantes de desarrollo de software que a traves de los nuevos conocimientos adquiridos
        queremos plasmar una idea de una aplicación que sirva como medio para todas aquellas personas que quieren 
        compartir conocimientos técnicos de diiversos temas y al mismo tiempo aprender de los conocimientos de los demás
        
    </p>

 </div>
 <a name="marcador3"></a>
 <h2 class="titulo3">Servicios</h2>

 <div  class="servicios">
    <div  class="servicios1">
    <img class="imgservicios" src="img/red.jpg" alt="">
    <div class="texto_servicios">
    <p>Encontraras grupos de personas que esten alineados con tus intereses que 
        puedan complementar tus conocimientos o tu los de ellos
    </p>
  </div>
   </div>
   <div  class="servicios1">
    <img class="imgservicios" src="img/periodico.jpg" alt="">
    <div class="texto_servicios">
    <p>En smart book encontrarás diversos conocimientos de los cuales se puede aprender
        de una forma interactiva, donde puedes dejar tu calificacion y apreciacion en los comentarios
    </p>
    </div>
    </div>
    <div class="servicios1">
    <img class="imgservicios" src="img/iconoP.jpg" alt="">
    <div class="texto_servicios">
    <p>Te da un espacio donde puedes compartir tus conocimientos técnicos.
        ¡Sé el engranaje de esta nueva revolución!
    </p>
    </div>
    </div>
    </div>

  <a name="marcador4"></a>
 <h2 class="titulo4">Contactenos</h2>
 
 <div class="contactenos">

 <form id="formulario">
    
  <div class="form-group">
    <img id="icon"src="../javascript/img/person_black_24dp.svg" alt=""><label for="formGroupExampleInput">Nombre*</label>
    
    <input type="text" class="form-control"  placeholder="ingresa tu nombre"> 

    <img id="icon" src="../javascript/img/mail_black_24dp.svg" alt=""><label for="exampleInputEmail1">Email*</label>
    <input type="email" class="form-control"  placeholder="Ingresa tu email">
    
    <img src="../javascript/img/create_black_24dp.svg" alt=""><label for="exampleFormControlTextarea1">Inquietud*</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"placeholder="Ingresa tu inquietud"></textarea>
  </div>
  <button type="submit" id="boton"class="btn btn-primary">Enviar</button>
 </form>
 
 <img  id="contactanos"src="img/contactar.jpg" alt="">
 </div> 
 



 <footer>@Derechos reservados de Sandra Mallerly Garcia Gutierrez y Jhon Fredy Medina</footer>
  

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</div>
</body>
</html>